### ISSUE TITLE
Support Webpack + CommonJS Package Manager

### ISSUE THREAD

**Issue by benoror** [gdi2290/angular-md5#8]
Hi Patrick!

I am learning Webpack + ES6 and in the process porting my app (main ideas taken [from here](http://angular-tips.com/blog/2015/06/using-angular-1-dot-x-with-es6-and-webpack/), [also here](http://www.shmck.com/webpack-angular-part-3/) and @kentcdodds's [egghead screencasts](https://egghead.io/series/angular-and-webpack-for-modular-applications)).

This package is a dependency of my project. Basically I want to be able to implement the following ES6 code:

```
import './login.css';

import angular from 'angular';
import uirouter from 'angular-ui-router';
import md5 from 'angular-md5'; /** this **/

import routing from './login.routes';
import LoginCtrl from './login.controller';

export default angular.module('app.main.login', [
		uirouter,
		md5
	])
  .config(routing)
  .controller('LoginCtrl', LoginCtrl)
  .name;
```

I've tried using the following code to support it:

```
if (typeof module !== "undefined" && typeof exports !== "undefined" && module.exports === exports){
  module.exports = 'angular-md5';
}
```
**Source: [ui-router release](https://github.com/angular-ui/ui-router/blob/master/release/angular-ui-router.js#L9)*

Actually I updated another  old dependency this same way, and worked fine: https://github.com/benoror/angular-urlify/commit/affc74b6ad8837d4aa88f3d0153dd70a717d2c6f

I tried the same with angular-md5: https://github.com/benoror/angular-md5/blob/master/lib/index.js#L2

But for some reason webpack compiles it wrong, and throws the following error:

![md5](http://i.imgur.com/fJCgUqL.png)

I can make a PR to support it, I just need some advice.

Thanks in advance. Cheers!

**Comment by benoror** [comment]
Support CommonJS Package Manager (solves #8)

Hi Patrick,

It needed some simple refactoring, I fixed it in the build target: https://github.com/gdi2290/angular-md5/compare/master...benoror:master

Apparently the issue is with the Grunt tooling, when building & concatenating the build, but I'm not sure which to blame.

**Comment by gdi2290** [comment]
can you make a pull-request?

**Comment by benoror** [comment]
Done, I made the adjustments for **uglify**

**Comment by gdi2290** [comment]
repo updated as `v0.1.8`
